//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTrainer
    {
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public string CourseDescription { get; set; }
        public string CourseLevels { get; set; }
        public string CourseLanguage { get; set; }
        public string CourseSkills { get; set; }
        public Nullable<int> CousrePrice { get; set; }
        public byte[] CourseThumbNail { get; set; }
    }
}
