//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udemy_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseUserFeedback
    {
        public Nullable<int> CourseId { get; set; }
        public string CourseReviews { get; set; }
        public Nullable<int> CourseRatings { get; set; }
        public string CourseComments { get; set; }
        public int ReviewId { get; set; }
    
        public virtual CourseTrainer CourseTrainer { get; set; }
    }
}
