//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udemy_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UdemyEntities4 : DbContext
    {
        public UdemyEntities4()
            : base("name=UdemyEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourseFeedBack> CourseFeedBacks { get; set; }
        public virtual DbSet<CourseMapping> CourseMappings { get; set; }
        public virtual DbSet<CourseTrainer> CourseTrainers { get; set; }
        public virtual DbSet<CourseUserFeedback> CourseUserFeedbacks { get; set; }
        public virtual DbSet<RoleMapping> RoleMappings { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        //public virtual ObjectResult<sp_GetAllCourse_Result> sp_GetAllCourse()
        //{
        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllCourse_Result>("sp_GetAllCourse");
        //}
    
        public virtual ObjectResult<sp_getCourse_Result> sp_getCourse()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getCourse_Result>("sp_getCourse");
        }
    }
}
